### ISSUE TITLE
How to run it on GPU?

### ISSUE THREAD

**Issue by yanchlu** [google-research/language#10]
I'm trying to use your code to train the model. However, when I run it, the program defaults to CPU instead of GPU. I only have GPU, but I don't know how to modify it. Could you please give me some advices?

**Comment by gisvl** [comment]
Hi @yanchlu, are you sure it's running on CPU, I had the same assumption, because of a print saying "training running on CPU", but in my opinion it is just a standard output to denote that it's not running on TPU, if you have GPU and you installed the GPU-Version of TF, it should run on your GPU.

**Comment by yanchlu** [comment]
@gisvl Thank you very much. Your point is correct. I have downloaded two versions of TF before, one is CPU-Version and one is GPU-Version.This led to some problems with the program that it doesn't run on GPU. Besides, as you said, "training running on CPU" is just a standard output.

**Comment by Jimntu** [comment]
Hi, I also download two versions of TensorFlow 1.14, one is CPU, and one is GPU. But the program still runs on CPU. Could you please tell me how can I make the program run on GPU? Thank you so much!
