### ISSUE TITLE
CANINE pre-training

### ISSUE THREAD

**Issue by david-waterworth** [google-research/language#106]
I'm quite keen to experiment with CANINE, but I need to pre-train on my own corpus. I'm using building sensor network point names so models pre-trained on standard sentences don't really transfer much useful context, and as the paper identifies it's quite difficult to implement tokenisation so I'd love to be able to use CANINE.

Do you have a timeline for the release of a pre-training script? I'm assuming I could use that to generate weights and then load into the Huggingface implementation. Ideally, I'd also disable the next sentence prediction - I'm training on records not sentences, the difference being there's no natural order so NSP doesn't really apply (although I could potentially substitute with records from the same system)

**Comment by jhclark-google** [comment]
Hi David -- Since this repo is shared across many repos (besides just Canine), I've been trying to route communication over email (which I check more frequently). Could we move this discussion to email?

**Comment by david-waterworth** [comment]
Absolutely, I'll send you an email.

**Comment by stefan-it** [comment]
Hi @david-waterworth and @jhclark-google ,

could you please update the issue here, whenever there's any update regarding to the pre-training code :thinking: I'm also highly interested in pre-training a CANINE model from scratch using my own corpus (different domain, that is definitely not covered in the released CANINE models) - would be awesome :hugs:

**Comment by syssel** [comment]
Hi @jhclark-google
I would like to echo @stefan-it  🙌
I am working on a domain with a high variance in orthography and is very interested in pretraining my own CANINE model that I can compare standard subword approaches.

**Comment by Filco306** [comment]
Hello there! I am also very interested in pre-training on my own corpus! Is there a timeline for this?

**Comment by thomas-ferraz** [comment]
Hi everyone! I'm interested on training CANINE in languages not covered today! Do you plan to release the pre-training code?
