### ISSUE TITLE
when will the code and data for "Systematic Generalization on gSCAN" be released?

### ISSUE THREAD

**Issue by chenkq7** [google-research/language#115]
Hi, Thank you for making this repository. After reading your great paper _[Systematic Generalization on gSCAN: What is Nearly Solved and What is Next?](https://arxiv.org/abs/2109.12243)_, I am very interested in your work. However, when I want to take a further look at the code and new dataset, I find the url in the paper footnotes is not available.

>1The code and data are available at https://github.com/google-research/language/tree/master/language/gscan.

Looking forward to the release of the code and data.

**Comment by fdelrio89** [comment]
I also would like to know this :)

**Comment by chenkq7** [comment]
the code and data is released.
