### ISSUE TITLE
how to train with this data

### ISSUE THREAD

**Issue by policeme** [google-research/language#30]
there are many answers include long answers and short answers, if I train a model, which answer should I use, it couldn't use all of the condidates long answers, if do that, the model can't converage.

**Comment by SeoHyeong** [comment]
Are you referring to long answer candidates? If so, according to [https://github.com/google-research-datasets/natural-questions/blob/master/README.md#long-answer-candidates](README), the model is supposed to find answer from long answer candidates, meaning that long answer candidates are not answers itself.
