### ISSUE TITLE
nq_eval.py file is missing

### ISSUE THREAD

**Issue by wmmxk** [google-research/language#34]
Thanks for publishing your code. It seems the ```nq_eval.py``` file is missing when I run this command: 
python -m natural_questions.nq_eval \
  --logtostderr \
  --gold_path=tiny-dev/nq-dev-sample.jsonl.gz \
  --predictions_path=bert_model_output/predictions.json

Could you also publish this file?

**Comment by SeoHyeong** [comment]
`nq_eval.py` is from `natural-questions` package. Here's the implementation (https://github.com/google-research-datasets/natural-questions/blob/master/nq_eval.py) if you need to take a look at details.
