### ISSUE TITLE
Examples with correct context retained: 0 of 0

### ISSUE THREAD

**Issue by zzj0402** [google-research/language#47]
## Environment

https://hub.docker.com/repository/docker/zzj0402/natural-questions-environment

## Running Script

```shell
python -m language.question_answering.bert_joint.prepare_nq_data \
  --logtostderr \
  --input_jsonl /root/data/v1.0/nq-train-??.jsonl.gz \
  --output_tfrecord ~/output_dir/nq-train.tfrecords-00000-of-00001 \
  --max_seq_length=512 \
  --include_unknowns=0.02 \
  --vocab_file=bert-joint-baseline/vocab-nq.txt \
  --max_contexts=8
```

### Console

`Examples with correct context retained: 0 of 0`

### File

~/output_dir/nq-train.tfrecords-00000-of-00001 is empty

**Comment by SeoHyeong** [comment]
try escaping question mark on the regex expression maybe?

**Comment by zzj0402** [comment]
> try escaping question mark on the regex expression maybe?

Everything works fine now.
