### ISSUE TITLE
TypeError: '<' not supported between instances of 'ScoreSummary' and 'ScoreSummary'

### ISSUE THREAD

**Issue by bicachu** [google-research/language#49]
I'm getting a TypeError when I run the run_nq script on the tiny-dev sample on Google Colabatory using Python 3.6 / TF 1.15. It's odd as I previously was able to run the script just fine and compute predictions but it seems to be failing now when it's producing the predictions and I'm not sure why as I didn't touch the script at all except for updating flags.

```I0303 18:14:12.365530 140077364746112 run_nq.py:1266] Computing predictions...
Traceback (most recent call last):
  File "run_nq.py", line 1444, in <module>
    tf.app.run()
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "run_nq.py", line 1434, in main
    [r._asdict() for r in all_results])
  File "run_nq.py", line 1270, in compute_pred_dict
    summary = compute_predictions(e)
  File "run_nq.py", line 1201, in compute_predictions
    score, summary, start_span, end_span = sorted(predictions, reverse=True)[0]
TypeError: '<' not supported between instances of 'ScoreSummary' and 'ScoreSummary'```

**Comment by cherry979988** [comment]
Hi! I encountered this same problem and I figured out this workaround by specifying the key for sorting.

`score, summary, start_span, end_span = sorted(predictions, reverse=True, key=lambda x: x[0])[0]`

I hope this is helpful to you :)

**Comment by bicachu** [comment]
> Hi! I encountered this same problem and I figured out this workaround by specifying the key for sorting.
> 
> `score, summary, start_span, end_span = sorted(predictions, reverse=True, key=lambda x: x[0])[0]`
> 
> I hope this is helpful to you :)

Thank you - this is! I was also able to do the same using a similar but different syntax as such:

`score, summary, start_span, end_span = sorted(predictions, reverse=True, key=operator.itemgetter(0))[0]`
