### ISSUE TITLE
Error: pip install bert-tensorflow natural-questions

### ISSUE THREAD

**Issue by ShuGao0810** [google-research/language#5]
Collecting wsgiref (from natural-questions)
  Using cached https://files.pythonhosted.org/packages/41/9e/309259ce8dff8c596e8c26df86dbc4e848b9249fd36797fd60be456f03fc/wsgiref-0.1.2.zip
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\as\AppData\Local\Temp\pip-install-bvrvsuv5\wsgiref\setup.py", line 5, in <module>
        import ez_setup
      File "C:\Users\as\AppData\Local\Temp\pip-install-bvrvsuv5\wsgiref\ez_setup\__init__.py", line 170
        print "Setuptools version",version,"or greater has been installed."
                                 ^
    SyntaxError: Missing parentheses in call to 'print'. Did you mean print("Setuptools version",version,"or greater has been installed.")?

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\as\AppData\Local\Temp\pip-install-bvrvsuv5\wsgiref\

**Comment by kentonl** [comment]
It looks like the `wsgiref` dependency is pre-packaged in python 3, but the `natural-questions` dependency is still trying to install it from pip. Can you try repeating the installation with the `--no-dependencies` flag?

**Comment by ShuGao0810** [comment]
Successfully installed with the --no-dependencies flag !
