### ISSUE TITLE
AttributeError: module 'tensorflow._api.v2.train' has no attribute 'Optimizer'

### ISSUE THREAD

**Issue by Syauri** [google-research/language#53]
Trying to run bert_joint on Google Colab but ran into AttributeError: module 'tensorflow._api.v2.train' has no attribute 'Optimizer'. I assume this is because Google colab is using a different version of tensorflow. What version do you use?

**Comment by soheeyang** [comment]
I just had the same issue a few minutes ago; I downgraded tensorflow to v1.15 and now the error is gone. I think the cause of the error is that tf.train.Optimizer is deprecated and removed in tensorflow v2.

**Comment by Syauri** [comment]
Yes downgrading helped! Thanks!
