### ISSUE TITLE
Training Instructions for xsp

### ISSUE THREAD

**Issue by aagohary** [google-research/language#64]
Hi,
Thanks for uploading the code of your paper "Exploring Unexplored Generalization Challenges for Cross-Database Semantic Parsing". I was wondering if you can share the instructions for pre-processing and training the model to re-produce the results in the papers. Thanks.

--Ahmed

**Comment by alsuhr-c** [comment]
Hi, 

We're working on writing instructions for replicating our experiments. Instructions for data download and preprocessing should be available in the master branch very soon; instructions for model training and evaluation will come a bit later.

Alane

**Comment by aagohary** [comment]
Thanks.
