### ISSUE TITLE
hi  i have questions about realm model 

### ISSUE THREAD

**Issue by paulrich1234** [google-research/language#72]
i have checked the realm_data  ,and it seams to no tf_hub module for doc embedding . i donot know  where to download  the module files .

thank you for your reply .

**Comment by kentonl** [comment]
The realm-data directory only contains the files used for pre-training. If you are looking for the already pre-trained REALM model, please see https://console.cloud.google.com/storage/browser/realm-data/cc_news_pretrained.

**Comment by paulrich1234** [comment]
> The realm-data directory only contains the files used for pre-training. If you are looking for the already pre-trained REALM model, please see https://console.cloud.google.com/storage/browser/realm-data/cc_news_pretrained.

hi  kentonl   ,i want to pre-training by myself use my own data ,but i think  i need a pre-training tf_hub module for docs embeddings in the first step(sh language/realm/local_launcher.sh refresh,it can not find files first time  in the ./out/export/tf_hub  when run it), i am looking the files it needs in  sh language/realm/local_launcher.sh refresh .

Thank you for your reply   .

**Comment by tinamola** [comment]
@paulrich1234 Did you find the solution? I'm having the same question.
