### ISSUE TITLE
running ORQA demo gives error

### ISSUE THREAD

**Issue by mchari** [google-research/language#87]
I am running the following command (using tensorflow 2.3.1 on linux)
python -m language.orqa.predict.orqa_demo \
  --model_dir=https://console.cloud.google.com/storage/browser/orqa-data/orqa_nq_model \
  --port=8080
but I get the error : 

tensorflow.python.framework.errors_impl.UnimplementedError: File system scheme 'https' not implemented (file: 'https://console.cloud.google.com/storage/browser/orqa-data/orqa_nq_model/params.json'

I replaced gs://... with https:// following the guidance in 
You can use gsutil to download from links with the gs:// prefix. You can also browse such links by replacing gs:// with https://console.cloud.google.com/storage/browser/ (requires signing in with any Google account).

**Comment by ioannist** [comment]
They are saying that you can download the files locally form your browser by replacing gs:// with https://console.cloud.google.com/storage/browser/

Once you download them locally form your browser (will require google login), you can then reference them as local files in your code.

**Comment by mchari** [comment]
Thanks. That's what I did.
