### ISSUE TITLE
Unicode error while running evaluation on tiny-dev dataset

### ISSUE THREAD

**Issue by graviraja** [google-research/language#9]
I have downloaded the tiny-dev dataset, preprocessed data and the pretrained model. while running evaluation code using the following command 

```
python -m language.question_answering.bert_joint.run_nq \
  --logtostderr \
  --bert_config_file=bert-joint-baseline/bert_config.json \
  --vocab_file=bert-joint-baseline/vocab-nq.txt \
  --predict_file=tiny-dev/nq-dev-sample.no-annot.jsonl.gz \
  --init_checkpoint=bert-joint-baseline/bert_joint.ckpt \
  --do_predict \
  --output_dir=bert_model_output
```
it is throwing following error.

![naturalqa_error](https://user-images.githubusercontent.com/7556119/57121876-e8848900-6d97-11e9-949c-91f5c24b2fc5.PNG)

**Comment by gisvl** [comment]
@graviraja did you manage to solve this issue? This is because you're probably using python3. I got over it changing a couple of lines, there are other python3 issues. For this one just replace "r" with "rb" in 
lines 865 and 867. The reason why is [here](https://github.com/tensorflow/tensorflow/issues/11312)

**Comment by graviraja** [comment]
@gisvl yes i solved it. Thank you for your input.

**Comment by renatoviolin** [comment]
@graviraja How did you solve the "TypeError: unsupported operand type(s) for +: 'zip' and 'list'" ?
I tried to cast to list, but fails inside sorted.
I remove the sorted and fails at end predictions.

**Comment by graviraja** [comment]
@renatoviolin  convert them into list first and then zip it.
